name: terraform-lint
on: 
  push:
  pull_request:
    branches:
      - master
jobs:
  lint:
    name: 'Terraform Lint'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: env.TERRAFORM_VERSION
      - name: Terraform Format
        run: terraform fmt -recursive -check -diff
        
